<?php

/**
 * @file
 * Contains acquia_lift_block.module.
 */

use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function acquia_lift_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.acquia_lift_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Some info about Acquia Lift Block') . '</p>';

      return $output;
  }
}

/**
 * Implements block_view_alter().
 */
function acquia_lift_block_block_view_alter(array &$build, BlockPluginInterface $block) {
  $build['#cache']['tags'] = ['liftblock'];
}
