<?php

/**
 * @file
 * Contains acquia_lift_block.module.
 */

use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function acquia_lift_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.acquia_lift_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Some info about Acquia Lift Block') . '</p>';

      return $output;
  }
}


/**
 * Implements hook_preprocess_block().
 */
function acquia_lift_block_preprocess_block(&$variables) {
  $id = $variables['elements']['#id'];
  $block = \Drupal\block\Entity\Block::load($id);

  if (method_exists($block, 'getVisibility')) {
    $visibility = $block->getVisibility();
    if (isset($visibility['acquia_lift_block_segment'])) {
      $variables['attributes']['class'][] = 'liftblock';
      $variables['#attached']['library'][] = 'acquia_lift_block/lift_block';
      $segments = $visibility['acquia_lift_block_segment']['segments'];
      foreach ($segments as $segment) {
        $variables['attributes']['class'][] = 'liftblock-' . $segment;
      }
    }
  }
}
